### ISSUE TITLE
Link field sources title from incorrect field

### ISSUE THREAD

**Issue by erzr** [erzr/jss-svelte#31]
The link field is currently pulling the title attribute value from the `class` field on the link. This attribute should source from the `title` field on the link. 

See the React Link implementation for how this field is sourced there: 
https://github.com/Sitecore/jss/blob/dev/packages/sitecore-jss-react/src/components/Link.tsx#L77

**Comment by jfmanuel** [comment]
Hi Adam,

I will fix this one.
Glad to contribute somehow.
Thanks!

**Comment by erzr** [comment]
Thanks @jfmanuel!
